name: organizer
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  intl: ^0.19.0
  shared_preferences: ^2.3.2
  supabase_flutter: ^2.8.0
  image_picker: ^1.1.2
  easy_localization: ^3.0.7

# our packages here
  my_melos_widgets: 0.0.1
# _______________________

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
  - assets/translations/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-VariableFont_opsz,wght.ttf
          weight: 100
        - asset: assets/fonts/Inter-VariableFont_opsz,wght.ttf
          weight: 200
        - asset: assets/fonts/Inter-VariableFont_opsz,wght.ttf
          weight: 300
        - asset: assets/fonts/Inter-VariableFont_opsz,wght.ttf
          weight: 400
        - asset: assets/fonts/Inter-VariableFont_opsz,wght.ttf
          weight: 500
        - asset: assets/fonts/Inter-VariableFont_opsz,wght.ttf
          weight: 600
        - asset: assets/fonts/Inter-VariableFont_opsz,wght.ttf
          weight: 700
        - asset: assets/fonts/Inter-VariableFont_opsz,wght.ttf
          weight: 800
        - asset: assets/fonts/Inter-VariableFont_opsz,wght.ttf
          weight: 900